global using Ametrin.Utils;
global using Ametrin.Utils.Optional;
global using MachineLearning.Data.Entry;
global using MachineLearning.Domain.Activation;
global using MachineLearning.Domain.Numerics;
global using MachineLearning.Model;
global using MachineLearning.Model.Embedding;
global using MachineLearning.Model.Layer.Initialization;
global using MachineLearning.Training;
global using MachineLearning.Training.Cost;
global using MachineLearning.Training.Optimization.Adam;
global using MachineLearning.Training.Optimization.AdamW;
global using MachineLearning.Training.Optimization.Nadam;
global using MachineLearning.Training.Optimization.SGDMomentum;
global using Weight = double;